name: Build and Deploy
on: [push] #监听push动作
# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '18'  # 这里可以根据需要设置为 18 或更高版本，如 20
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
    - name: vuepress-deploy
      uses: xiaoke/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}} #刚刚生成的secret
        TARGET_REPO: xiaokekeq/Blog.git #仓库地址
        TARGET_BRANCH: gh-pages #目标分支，gh-pages一般用来存放生成的静态文件
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/ #生成的静态文件存放目录